import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  firstName: "",
  lastName: "",
  avater: "",
  email: "",
  username: "",
  showBalance: "",
  role: "",
  wallet: {}
}
export const userDataSlice = createSlice({
  name: 'userData',
  initialState: {
    userData: initialState
  },
  reducers: {
    setUserData: (state, action) => {
      console.log(action.payload);
      state.userData = {...state.userData, ...action.payload}
    },
    clearUserData: (state, action) => {
      state.userData = initialState
    }
  },
});

// exporting actions auto generated by redux-toolkit
export const { setUserData, clearUserData } = userDataSlice.actions;

export default userDataSlice.reducer
