"use client"
import type { Metadata } from 'next'
import ImportBsJS from './importBSJs'
import './globals.css'
import Providers from '@/utils/provider'


/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossOrigin="anonymous" referrerPolicy="no-referrer"
        />
      </head>
      <body>
        <ImportBsJS />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
