
@baseUrl = http://localhost:3000/api/v1/

# @name getBranches
GET {{baseUrl}}/branch HTTP/1.1

###


# @name createBranch
POST {{baseUrl}}/branch HTTP/1.1
Content-Type: "application/json"

{
  "code": "test-code",
  "name": "test-Branch-name",
  "email": "test-email@gmail.com",
  "address": "test-Branch address",
  "logo": ""
}

###

@branchId = 939dfd7d-ea5e-46a0-994c-46815c9f892b

# @name getBranch
GET {{baseUrl}}/branch/{{branchId}} HTTP/1.1

###

# @name updateBranch
PATCH  {{baseUrl}}/branch/{{branchId}} HTTP/1.1
Content-Type: "application/json"

{
  "code": "test-code-updated"
}

###

# @name deleteCompany
DELETE  {{baseUrl}}/branch/{{branchId}}
